### ISSUE TITLE
Emoji suggestions interfere with sending messages and cannot be disabled

### ISSUE THREAD

**Issue by snowkat** [tigase/beagle-im#100]
**Is your feature request related to a problem? Please describe.**
Starting with at least version 5.1-b145 on macOS Big Sur, entering an emote such as `:)`, `:O`, etc. will cause an emoji suggestion to appear. If this emote is at the end of a message, pressing Return will cause the suggestion to be inserted instead of sending the message. This can only be avoided by pressing Esc, then Return.

I have all suggestions and spellchecking turned off in the OS, and tried disabling "Show Emoticons" in BeagleIM preferences. There doesn't seem to be another option for disabling these suggestions or stopping them from being used when pressing Return.

**Describe the solution you'd like**
I believe the best solution would be the ability to disable emoji suggestions in Preferences. 

**Describe alternatives you've considered**
Discord's functionality is more involved, but could work as an alternative:
* "Automatically convert emoticons in your messages to emoji" as an option in Preferences. If this option is on, emotes such as `:)` and `:-)` will be converted to emoji.
* When this option is off, shortcode suggestions only start on the second message. Using `:smile:` as an example, `:s` won't show suggestions, but `:sm` will start showing suggestions.

**Additional context**

**Comment by hantu85** [comment]
Replacing `:)`, `:-)` with emoji before displaying (what you are suggesting) is causing issues as the app has no idea if the replacement should be done or not. This information only has a message sender, so that is up to the sender to use suggestions and user correct emoji or not.

This feature was added to deprecate in the future automatic replacement of `:)` and `:-)` in the received messages, which you suggested as an alternative to what is currently done.

If there is a need to disable suggestions for emoji, then we may consider adding an option.

Displaying suggestions after just one character is intentional to help people not used to using shortcodes (easier to find a correct shortcode).

**Comment by hantu85** [comment]
In version 5.1-b147 option to disable emoticon suggestions was added.
