### ISSUE TITLE
Add MUC Icon Description

### ISSUE THREAD

**Issue by adamflott** [tigase/beagle-im#106]
I run my own XMPP server and while learning to properly configure it I occasionally have an yellow/orange dot on 2 head icon near the top of a MUC (on OSX). I know when it's green things are working, but when it is yellow/orange I have no idea what that means. However I do know that I can not send messages in the chat when it is yellow.

I would like either a description(notification?) on hover or even under the icon to indicate something isn't set up correctly.

**Comment by hantu85** [comment]
The yellow dot means that reconnection is in progress (there was no failure yet, so there is nothing we can tell you). 

In some cases, it may happen that the server will return an error but the type of the error would indicate that it is a temporary error, in this case, BeagleIM will just try to reconnect (and the account would still be marked with an `orange` dot - as reconnection is still in progress).

If you are troubleshooting issues with your XMPP server, you should hold `Option` key and click on the main menu item `Window` > `XML Console` > account. This will open an XML console with the full log of XML exchange between BeagleIM and the XMPP server since the console window was opened. This should help you investigate the issue and fix it.

**Comment by hantu85** [comment]
I'm aware of the issues with Openfire and TLS 1.3 when using the latest stable versions of Siskin IM and Beagle IM but those should be fixed soon and those would not cause 1-way authentication as it looks like the clients are not aware that they are fully authenticated - I would suggest checking XMPP stream in parts related to the resource binding or session establishment parts. Maybe there is something that clients do not like or accept?

**Comment by hantu85** [comment]
I do recall having a yellow dot near the MUC icon, if the MUC itself was not sending the correct presence to the clients, notifying them the room was properly joined. If I recall correctly, it was related to the missing `<presence>` from the MUC containing status code `110` and it might be related to the case when more than one client was joining the same MUC room from the same account.

I also do recall, that the issue was somehow related only to the rooms with a lot of messages and caused message throttling kicking in (on our local server).

**Comment by adamflott** [comment]
I changed from ejabberd 21.04 to prosody 0.12 and all my connection issues have vanished. Closing.
