### ISSUE TITLE
Beagle 4.1 stopped decrypting OMEMO messages

### ISSUE THREAD

**Issue by michaelblyons** [tigase/beagle-im#69]
I'm not sure what happened. When I receive messages from self or another contact, I get the OMEMO link and a decryption failure.

Also super weird: I no longer have any device fingerprints in Beagle. Clicking on the ⚙️ does nothing. Only "Close" works.

<img width="344" alt="Screen Shot 2020-12-23 at 2 22 05 PM" src="https://user-images.githubusercontent.com/2701605/103030654-26798680-4554-11eb-968d-553faf078977.png">

I'm still on 4.1 (110), and I'm _pretty_ sure I never installed the Beta version. If there's something you'd like me to check that would verify whether I've ever installed a DB-migrated Beta, I'm happy to look into it. MacOS Catalina.

**Comment by michaelblyons** [comment]
Can I have some debug suggestions, please? Beagle is unusable right now.

**Comment by hantu85** [comment]
It is hard to tell what actually is causing this issue. I do see that BeagleIM is not displaying OMEMO fingerprints but it looks like all fingerprints were removed from this account.

Do you have any other client connected to this account working OMEMO?

**Comment by michaelblyons** [comment]
Yes. My phone has Conversations, and it is still working.

If I were even able to add a brand new OMEMO key (and then reload my other device keys), I could move to that one and revoke the old one. But I can't figure out how.

**Comment by hantu85** [comment]
I'm assuming that you do have an account in the preferences dialog selected. 

In this case, it looks like something caused OMEMO fingerprints to be removed from your device and it is not able to fetch existing keys nor generate a new key.

I would suggest to check XML exchanges while client connects to the XMPP server to make sure it actually tries to fetch OMEMO keys and check server response if it is correct.

If that would not help, another idea would be to remove and then add XMPP account to BeagleIM.

And if that would not help, then just drop BeagleIM database as this issue may be caused by some weird entry in the OMEMO identities table.

**Comment by michaelblyons** [comment]
Ooh, this is interesting. Disconnecting and reconnecting repopulates the OMEMO dialog. I did this once and sent a message that failed to decrypt. All the fingerprints had disappeared again.

Now I've reconnected a second time, and things _seem_ to be working.

Thanks!
