### ISSUE TITLE
Beagle fails to connect, but doesn't report why

### ISSUE THREAD

**Issue by raucao** [tigase/beagle-im#71]
Recently, Beagle stopped connecting to a working XMPP server, but instead of reporting a connection error to the user, it just indicates disconnected state via grey dots.

 - OS: macOS 10.14.6
 - Version 4.1[110]

Opening the log directory from the settings dialog yields an empty directory. Where can I find logs and/or how can I enable debug logs?

**Comment by hantu85** [comment]
BeagleIM tries to connected every X seconds (ie. delaying next retry if previous attempt fails). Due to that there is no point to notify user of an error which does not require user interaction, ie. failed TCP connection or the XMPP error that is possible to be fixed after another reconnection (this information is reported by XMPP protocol).

If there would be an error requiring user interaction, user would be notified.

If you wish to check XMPP protocol exchange for the account, please open `Window` menu while holding `Option` key and then and select `XML Console` and proper account. In newly opened window you will see the XML exchange for this account which happened since the window was opened (just wait to see new entries).

If no entries are visible, then most likely there is an issue with TCP connection or DNS SRV resolution.

**Comment by raucao** [comment]
The XML console is empty, because the client cannot establish a connection in the first place. The user is sitting in front of the client for a few days now, not knowing why it won't connect.

> If no entries are visible, then most likely there is an issue with TCP connection or DNS SRV resolution.

Yes, and I'm sure it's possible to enable and access debug logs for the connection, as e.g. seen in https://github.com/tigase/beagle-im/issues/40.

**Comment by hantu85** [comment]
Logs gathered in #40 are printed to the standard output (terminal) when BeagleIM is launched from command line
