### ISSUE TITLE
Error trying to modify the profile settings

### ISSUE THREAD

**Issue by nicfab** [tigase/beagle-im#79]
Editing the profile settings Beagle gives the error as I describe below.
I tried to set a picture as the image profile related to my IM account.
However, the IM client returned an error and precisely "**Server returned an error: not_acceptable**".
I attach an image to be more precise.
I tried with another XMPP client, and it's possible to edit the profile details.

<img width="257" alt="Screenshot 2021-03-13 at 17 33 35" src="https://user-images.githubusercontent.com/24752671/111182091-de945980-85ae-11eb-88f9-c382704a7dba.png">

**Comment by hantu85** [comment]
BeagleIM uses VCard4 for the publication of VCard and PEP for avatar publication, so it may happen that other clients are using different XEPs (ie. VCardTemp) and due to that, it works with them while it does not work with BeagleIM.

As for submitting issues, please follow the templates that we provide and fill them in to provide relevant details.
